import { styleTags, tags as t } from '@lezer/highlight';

export const nsisHighlighting = styleTags({
	CommandName: t.keyword,
	'Function FunctionEnd Section SectionEnd SectionGroup SectionGroupEnd PageEx PageExEnd Var': t.keyword,
	PreprocKeyword: t.processingInstruction,
	PreprocIf: t.processingInstruction,
	PreprocElse: t.processingInstruction,
	PreprocEndif: t.processingInstruction,
	PreprocMacro: t.processingInstruction,
	PreprocMacroEnd: t.processingInstruction,
	'MacroOpen MacroMid MacroClose MacroCase MacroBreak': t.controlKeyword,
	'MacroCall/DefineReference': t.macroName,
	Constant: t.constant(t.name),
	ArgumentValue: t.atom,
	Operator: t.operator,
	Variable: t.variableName,
	DefineReference: t.special(t.variableName),
	LangStringReference: t.special(t.string),
	Flag: t.attributeName,
	Number: t.number,
	String: t.string,
	RawString: t.string,
	BacktickString: t.string,
	'DQEscape SQEscape BTEscape': t.escape,
	'DQVariable SQVariable BTVariable': t.variableName,
	'DQDefineRef SQDefineRef BTDefineRef': t.special(t.variableName),
	'DQLangRef SQLangRef BTLangRef': t.special(t.string),
	LineComment: t.lineComment,
	BlockComment: t.blockComment,
	Label: t.labelName,
	LabelReference: t.labelName,
	'PluginCall/Identifier': t.className,
	'::': t.punctuation,
});
