import { type CompletionContext, completeFromList } from '@codemirror/autocomplete';
import {
	foldInside,
	foldNodeProp,
	indentNodeProp,
	LanguageSupport,
	LRLanguage,
	syntaxTree,
	type TreeIndentContext,
} from '@codemirror/language';
import { nsisHighlighting } from './highlight.ts';
import { dedentOn } from './macro-specializers.ts';
import { parser } from './parser.ts';
import { specializeIdentifier, specializeIdentifierLoose } from './specializers.ts';

function blockIndent(closingPattern: RegExp) {
	return (cx: TreeIndentContext) => {
		if (closingPattern.test(cx.textAfter)) return cx.baseIndent;
		return cx.baseIndent + cx.unit;
	};
}

/** Alternation of the bare names of every macro a `LogicBlock` dedents on, i.e. its closers and mids. */
const macroDedentNames = [...dedentOn].map((macro) => macro.slice('${'.length, -'}'.length)).join('|');

const macroDedentPattern = new RegExp(`^\\s*\\$\\{(?:${macroDedentNames})\\}`, 'i');

const parserProps = [
	nsisHighlighting,
	indentNodeProp.add({
		FunctionBlock: blockIndent(/^\s*FunctionEnd\b/i),
		SectionBlock: blockIndent(/^\s*SectionEnd\b/i),
		SectionGroupBlock: blockIndent(/^\s*SectionGroupEnd\b/i),
		PageExBlock: blockIndent(/^\s*PageExEnd\b/i),
		MacroBlock: blockIndent(/^\s*!macroend\b/i),
		PreprocConditional: blockIndent(/^\s*!(?:endif|else)\b/i),
		LogicBlock: blockIndent(macroDedentPattern),
	}),
	foldNodeProp.add({
		FunctionBlock: foldInside,
		SectionBlock: foldInside,
		SectionGroupBlock: foldInside,
		PageExBlock: foldInside,
		MacroBlock: foldInside,
		LogicBlock: foldInside,
		PreprocConditional: foldInside,
		BlockComment: foldInside,
	}),
];

const languageData = {
	commentTokens: { line: '#', block: { open: '/*', close: '*/' } },
	closeBrackets: { brackets: ['(', '[', '{', '"', "'", '`'] },
	indentOnInput: new RegExp(
		`^\\s*(?:FunctionEnd|SectionEnd|SectionGroupEnd|PageExEnd|!(?:macroend|endif|else)|\\$\\{(?:${macroDedentNames})\\})\\s*$`,
		'i',
	),
};

export const nsisLanguage = LRLanguage.define({
	name: 'nsis',
	parser: parser.configure({
		props: parserProps,
		specializers: [{ from: specializeIdentifier, to: specializeIdentifierLoose }],
	}),
	languageData,
});

export const nsisLanguageStrict = LRLanguage.define({
	name: 'nsis',
	parser: parser.configure({
		props: parserProps,
	}),
	languageData,
});

const commands = [
	'Abort',
	'AddBrandingImage',
	'AddSize',
	'AllowRootDirInstall',
	'AllowSkipFiles',
	'AutoCloseWindow',
	'BGFont',
	'BGGradient',
	'BrandingText',
	'BringToFront',
	'Call',
	'CallInstDLL',
	'Caption',
	'ChangeUI',
	'CheckBitmap',
	'ClearErrors',
	'CompletedText',
	'ComponentText',
	'CopyFiles',
	'CPU',
	'CRCCheck',
	'CreateDirectory',
	'CreateFont',
	'CreateShortCut',
	'Delete',
	'DeleteINISec',
	'DeleteINIStr',
	'DeleteRegKey',
	'DeleteRegValue',
	'DetailPrint',
	'DetailsButtonText',
	'DirText',
	'DirVar',
	'DirVerify',
	'EnableWindow',
	'EnumRegKey',
	'EnumRegValue',
	'Exch',
	'Exec',
	'ExecShell',
	'ExecShellWait',
	'ExecWait',
	'ExpandEnvStrings',
	'File',
	'FileBufSize',
	'FileClose',
	'FileErrorText',
	'FileOpen',
	'FileRead',
	'FileReadByte',
	'FileReadUTF16LE',
	'FileReadWord',
	'FileSeek',
	'FileWrite',
	'FileWriteByte',
	'FileWriteUTF16LE',
	'FileWriteWord',
	'FindClose',
	'FindFirst',
	'FindNext',
	'FindWindow',
	'FlushINI',
	'Function',
	'FunctionEnd',
	'GetCurInstType',
	'GetCurrentAddress',
	'GetDlgItem',
	'GetDLLVersion',
	'GetDLLVersionLocal',
	'GetErrorLevel',
	'GetFileTime',
	'GetFileTimeLocal',
	'GetFullPathName',
	'GetFunctionAddress',
	'GetInstDirError',
	'GetKnownFolderPath',
	'GetLabelAddress',
	'GetRegView',
	'GetShellVarContext',
	'GetTempFileName',
	'GetWinVer',
	'Goto',
	'HideWindow',
	'Icon',
	'IfAbort',
	'IfAltRegView',
	'IfErrors',
	'IfFileExists',
	'IfRebootFlag',
	'IfRtlLanguage',
	'IfShellVarContextAll',
	'IfSilent',
	'InitPluginsDir',
	'InstallButtonText',
	'InstallColors',
	'InstallDir',
	'InstallDirRegKey',
	'InstProgressFlags',
	'InstType',
	'InstTypeGetText',
	'InstTypeSetText',
	'Int64Cmp',
	'Int64CmpU',
	'Int64Fmt',
	'IntCmp',
	'IntCmpU',
	'IntFmt',
	'IntOp',
	'IntPtrCmp',
	'IntPtrCmpU',
	'IntPtrOp',
	'IsWindow',
	'LangString',
	'LicenseBkColor',
	'LicenseData',
	'LicenseForceSelection',
	'LicenseLangString',
	'LicenseText',
	'LoadAndSetImage',
	'LoadLanguageFile',
	'LockWindow',
	'LogSet',
	'LogText',
	'ManifestAppendCustomString',
	'ManifestDisableWindowFiltering',
	'ManifestDPIAware',
	'ManifestDPIAwareness',
	'ManifestGdiScaling',
	'ManifestLongPathAware',
	'ManifestMaxVersionTested',
	'ManifestSupportedOS',
	'MessageBox',
	'MiscButtonText',
	'Name',
	'Nop',
	'OutFile',
	'Page',
	'PageCallbacks',
	'PageEx',
	'PageExEnd',
	'PEAddResource',
	'PEDllCharacteristics',
	'PERemoveResource',
	'PESubsysVer',
	'Pop',
	'Push',
	'Quit',
	'ReadEnvStr',
	'ReadINIStr',
	'ReadMemory',
	'ReadRegDWORD',
	'ReadRegStr',
	'Reboot',
	'RegDLL',
	'Rename',
	'RequestExecutionLevel',
	'ReserveFile',
	'Return',
	'RMDir',
	'SearchPath',
	'Section',
	'SectionEnd',
	'SectionGroup',
	'SectionGroupEnd',
	'SectionGetFlags',
	'SectionGetInstTypes',
	'SectionGetSize',
	'SectionGetText',
	'SectionIn',
	'SectionInstType',
	'SectionSetFlags',
	'SectionSetInstTypes',
	'SectionSetSize',
	'SectionSetText',
	'SendMessage',
	'SetAutoClose',
	'SetBrandingImage',
	'SetCompress',
	'SetCompressionLevel',
	'SetCompressor',
	'SetCompressorDictSize',
	'SetCtlColors',
	'SetCurInstType',
	'SetDatablockOptimize',
	'SetDateSave',
	'SetDetailsPrint',
	'SetDetailsView',
	'SetErrorLevel',
	'SetErrors',
	'SetFileAttributes',
	'SetFont',
	'SetOutPath',
	'SetOverwrite',
	'SetRebootFlag',
	'SetRegView',
	'SetShellVarContext',
	'SetSilent',
	'ShowInstDetails',
	'ShowUninstDetails',
	'ShowWindow',
	'SilentInstall',
	'SilentUnInstall',
	'Sleep',
	'SpaceTexts',
	'StrCmp',
	'StrCmpS',
	'StrCpy',
	'StrLen',
	'SubCaption',
	'Target',
	'Unicode',
	'UnsafeStrCpy',
	'UninstallButtonText',
	'UninstallCaption',
	'UninstallIcon',
	'UninstallSubCaption',
	'UninstallText',
	'UninstPage',
	'UnRegDLL',
	'Var',
	'VIAddVersionKey',
	'VIFileVersion',
	'VIProductVersion',
	'WindowIcon',
	'WriteINIStr',
	'WriteRegBin',
	'WriteRegDWORD',
	'WriteRegExpandStr',
	'WriteRegMultiStr',
	'WriteRegNone',
	'WriteRegStr',
	'WriteUninstaller',
	'XPStyle',
];

const preprocDirectives = [
	'!addincludedir',
	'!addplugindir',
	'!appendfile',
	'!appendmemfile',
	'!assert',
	'!cd',
	'!define',
	'!delfile',
	'!echo',
	'!else',
	'!endif',
	'!error',
	'!execute',
	'!finalize',
	'!getdllversion',
	'!gettlbversion',
	'!if',
	'!ifdef',
	'!ifndef',
	'!ifmacrodef',
	'!ifmacrondef',
	'!include',
	'!insertmacro',
	'!macro',
	'!macroend',
	'!macroundef',
	'!makensis',
	'!packhdr',
	'!pragma',
	'!searchparse',
	'!searchreplace',
	'!system',
	'!tempfile',
	'!undef',
	'!uninstfinalize',
	'!verbose',
	'!warning',
];

const stringNodeNames = new Set(['String', 'RawString', 'BacktickString']);

const commandCompletion = completeFromList(
	commands
		.map((c) => ({ label: c, type: 'keyword' }))
		.concat(preprocDirectives.map((d) => ({ label: d, type: 'keyword' }))),
);

function nsisCompletion(context: CompletionContext) {
	const node = syntaxTree(context.state).resolveInner(context.pos, -1);

	if (stringNodeNames.has(node.type.name) || (node.parent && stringNodeNames.has(node.parent.type.name))) {
		return null;
	}

	return commandCompletion(context);
}

export function nsis(config?: { strict?: boolean }) {
	const language = config?.strict ? nsisLanguageStrict : nsisLanguage;
	return new LanguageSupport(language, [language.data.of({ autocomplete: nsisCompletion })]);
}
