import {
	ArgumentValue,
	CommandName,
	Constant,
	// biome-ignore lint/suspicious/noShadowRestrictedNames: Function is a valid NSIS identifier
	Function,
	FunctionEnd,
	PageEx,
	PageExEnd,
	PreprocElse,
	PreprocEndif,
	PreprocIf,
	PreprocKeyword,
	PreprocMacro,
	PreprocMacroEnd,
	Section,
	SectionEnd,
	SectionGroup,
	SectionGroupEnd,
	Var,
} from './parser.terms.ts';

const keywords: Record<string, number> = {
	Function,
	FunctionEnd,
	Section,
	SectionEnd,
	SectionGroup,
	SectionGroupEnd,
	PageEx,
	PageExEnd,
	Var,

	Abort: CommandName,
	AddBrandingImage: CommandName,
	AddSize: CommandName,
	AllowRootDirInstall: CommandName,
	AllowSkipFiles: CommandName,
	AutoCloseWindow: CommandName,
	BGFont: CommandName,
	BGGradient: CommandName,
	BrandingText: CommandName,
	BringToFront: CommandName,
	Call: CommandName,
	CallInstDLL: CommandName,
	Caption: CommandName,
	ChangeUI: CommandName,
	CheckBitmap: CommandName,
	ClearErrors: CommandName,
	CompletedText: CommandName,
	ComponentText: CommandName,
	CopyFiles: CommandName,
	CPU: CommandName,
	CRCCheck: CommandName,
	CreateDirectory: CommandName,
	CreateFont: CommandName,
	CreateShortCut: CommandName,
	Delete: CommandName,
	DeleteINISec: CommandName,
	DeleteINIStr: CommandName,
	DeleteRegKey: CommandName,
	DeleteRegValue: CommandName,
	DetailPrint: CommandName,
	DetailsButtonText: CommandName,
	DirText: CommandName,
	DirVar: CommandName,
	DirVerify: CommandName,
	EnableWindow: CommandName,
	EnumRegKey: CommandName,
	EnumRegValue: CommandName,
	Exch: CommandName,
	Exec: CommandName,
	ExecShell: CommandName,
	ExecShellWait: CommandName,
	ExecWait: CommandName,
	ExpandEnvStrings: CommandName,
	File: CommandName,
	FileBufSize: CommandName,
	FileClose: CommandName,
	FileErrorText: CommandName,
	FileOpen: CommandName,
	FileRead: CommandName,
	FileReadByte: CommandName,
	FileReadUTF16LE: CommandName,
	FileReadWord: CommandName,
	FileSeek: CommandName,
	FileWrite: CommandName,
	FileWriteByte: CommandName,
	FileWriteUTF16LE: CommandName,
	FileWriteWord: CommandName,
	FindClose: CommandName,
	FindFirst: CommandName,
	FindNext: CommandName,
	FindWindow: CommandName,
	FlushINI: CommandName,
	GetCurInstType: CommandName,
	GetCurrentAddress: CommandName,
	GetDlgItem: CommandName,
	GetDLLVersion: CommandName,
	GetDLLVersionLocal: CommandName,
	GetErrorLevel: CommandName,
	GetFileTime: CommandName,
	GetFileTimeLocal: CommandName,
	GetFullPathName: CommandName,
	GetFunctionAddress: CommandName,
	GetInstDirError: CommandName,
	GetKnownFolderPath: CommandName,
	GetLabelAddress: CommandName,
	GetRegView: CommandName,
	GetShellVarContext: CommandName,
	GetTempFileName: CommandName,
	GetWinVer: CommandName,
	Goto: CommandName,
	HideWindow: CommandName,
	Icon: CommandName,
	IfAbort: CommandName,
	IfAltRegView: CommandName,
	IfErrors: CommandName,
	IfFileExists: CommandName,
	IfRebootFlag: CommandName,
	IfRtlLanguage: CommandName,
	IfShellVarContextAll: CommandName,
	IfSilent: CommandName,
	InitPluginsDir: CommandName,
	InstallButtonText: CommandName,
	InstallColors: CommandName,
	InstallDir: CommandName,
	InstallDirRegKey: CommandName,
	InstProgressFlags: CommandName,
	InstType: CommandName,
	InstTypeGetText: CommandName,
	InstTypeSetText: CommandName,
	Int64Cmp: CommandName,
	Int64CmpU: CommandName,
	Int64Fmt: CommandName,
	IntCmp: CommandName,
	IntCmpU: CommandName,
	IntFmt: CommandName,
	IntOp: CommandName,
	IntPtrCmp: CommandName,
	IntPtrCmpU: CommandName,
	IntPtrOp: CommandName,
	IsWindow: CommandName,
	LangString: CommandName,
	LicenseBkColor: CommandName,
	LicenseData: CommandName,
	LicenseForceSelection: CommandName,
	LicenseLangString: CommandName,
	LicenseText: CommandName,
	LoadAndSetImage: CommandName,
	LoadLanguageFile: CommandName,
	LockWindow: CommandName,
	LogSet: CommandName,
	LogText: CommandName,
	ManifestAppendCustomString: CommandName,
	ManifestDisableWindowFiltering: CommandName,
	ManifestDPIAware: CommandName,
	ManifestDPIAwareness: CommandName,
	ManifestGdiScaling: CommandName,
	ManifestLongPathAware: CommandName,
	ManifestMaxVersionTested: CommandName,
	ManifestSupportedOS: CommandName,
	MessageBox: CommandName,
	MiscButtonText: CommandName,
	Name: CommandName,
	Nop: CommandName,
	OutFile: CommandName,
	Page: CommandName,
	PageCallbacks: CommandName,
	PEAddResource: CommandName,
	PEDllCharacteristics: CommandName,
	PERemoveResource: CommandName,
	PESubsysVer: CommandName,
	Pop: CommandName,
	Push: CommandName,
	Quit: CommandName,
	ReadEnvStr: CommandName,
	ReadINIStr: CommandName,
	ReadMemory: CommandName,
	ReadRegDWORD: CommandName,
	ReadRegStr: CommandName,
	Reboot: CommandName,
	RegDLL: CommandName,
	Rename: CommandName,
	RequestExecutionLevel: CommandName,
	ReserveFile: CommandName,
	Return: CommandName,
	RMDir: CommandName,
	SearchPath: CommandName,
	SectionGetFlags: CommandName,
	SectionGetInstTypes: CommandName,
	SectionGetSize: CommandName,
	SectionGetText: CommandName,
	SectionIn: CommandName,
	SectionInstType: CommandName,
	SectionSetFlags: CommandName,
	SectionSetInstTypes: CommandName,
	SectionSetSize: CommandName,
	SectionSetText: CommandName,
	SendMessage: CommandName,
	SetAutoClose: CommandName,
	SetBrandingImage: CommandName,
	SetCompress: CommandName,
	SetCompressionLevel: CommandName,
	SetCompressor: CommandName,
	SetCompressorDictSize: CommandName,
	SetCtlColors: CommandName,
	SetCurInstType: CommandName,
	SetDatablockOptimize: CommandName,
	SetDateSave: CommandName,
	SetDetailsPrint: CommandName,
	SetDetailsView: CommandName,
	SetErrorLevel: CommandName,
	SetErrors: CommandName,
	SetFileAttributes: CommandName,
	SetFont: CommandName,
	SetOutPath: CommandName,
	SetOverwrite: CommandName,
	SetRebootFlag: CommandName,
	SetRegView: CommandName,
	SetShellVarContext: CommandName,
	SetSilent: CommandName,
	ShowInstDetails: CommandName,
	ShowUninstDetails: CommandName,
	ShowWindow: CommandName,
	SilentInstall: CommandName,
	SilentUnInstall: CommandName,
	Sleep: CommandName,
	SpaceTexts: CommandName,
	StrCmp: CommandName,
	StrCmpS: CommandName,
	StrCpy: CommandName,
	StrLen: CommandName,
	SubCaption: CommandName,
	Target: CommandName,
	Unicode: CommandName,
	UnsafeStrCpy: CommandName,
	UninstallButtonText: CommandName,
	UninstallCaption: CommandName,
	UninstallIcon: CommandName,
	UninstallSubCaption: CommandName,
	UninstallText: CommandName,
	UninstPage: CommandName,
	UnRegDLL: CommandName,
	VIAddVersionKey: CommandName,
	VIFileVersion: CommandName,
	VIProductVersion: CommandName,
	WindowIcon: CommandName,
	WriteINIStr: CommandName,
	WriteRegBin: CommandName,
	WriteRegDWORD: CommandName,
	WriteRegExpandStr: CommandName,
	WriteRegMultiStr: CommandName,
	WriteRegNone: CommandName,
	WriteRegStr: CommandName,
	WriteUninstaller: CommandName,
	XPStyle: CommandName,

	'!addincludedir': PreprocKeyword,
	'!addplugindir': PreprocKeyword,
	'!appendfile': PreprocKeyword,
	'!appendmemfile': PreprocKeyword,
	'!assert': PreprocKeyword,
	'!cd': PreprocKeyword,
	'!define': PreprocKeyword,
	'!delfile': PreprocKeyword,
	'!echo': PreprocKeyword,
	'!error': PreprocKeyword,
	'!execute': PreprocKeyword,
	'!finalize': PreprocKeyword,
	'!getdllversion': PreprocKeyword,
	'!gettlbversion': PreprocKeyword,
	'!include': PreprocKeyword,
	'!insertmacro': PreprocKeyword,
	'!macroundef': PreprocKeyword,
	'!makensis': PreprocKeyword,
	'!packhdr': PreprocKeyword,
	'!pragma': PreprocKeyword,
	'!searchparse': PreprocKeyword,
	'!searchreplace': PreprocKeyword,
	'!system': PreprocKeyword,
	'!tempfile': PreprocKeyword,
	'!undef': PreprocKeyword,
	'!uninstfinalize': PreprocKeyword,
	'!verbose': PreprocKeyword,
	'!warning': PreprocKeyword,

	'!if': PreprocIf,
	'!ifdef': PreprocIf,
	'!ifndef': PreprocIf,
	'!ifmacrodef': PreprocIf,
	'!ifmacrondef': PreprocIf,

	'!else': PreprocElse,
	'!endif': PreprocEndif,
	'!macro': PreprocMacro,
	'!macroend': PreprocMacroEnd,

	admin: ArgumentValue,
	all: ArgumentValue,
	'amd64-unicode': ArgumentValue,
	auto: ArgumentValue,
	both: ArgumentValue,
	bottom: ArgumentValue,
	bzip2: ArgumentValue,
	colored: ArgumentValue,
	components: ArgumentValue,
	current: ArgumentValue,
	custom: ArgumentValue,
	directory: ArgumentValue,
	false: ArgumentValue,
	force: ArgumentValue,
	hide: ArgumentValue,
	highest: ArgumentValue,
	ifdiff: ArgumentValue,
	ifnewer: ArgumentValue,
	instfiles: ArgumentValue,
	lastused: ArgumentValue,
	leave: ArgumentValue,
	left: ArgumentValue,
	license: ArgumentValue,
	listonly: ArgumentValue,
	lzma: ArgumentValue,
	nevershow: ArgumentValue,
	none: ArgumentValue,
	normal: ArgumentValue,
	notset: ArgumentValue,
	off: ArgumentValue,
	on: ArgumentValue,
	open: ArgumentValue,
	print: ArgumentValue,
	right: ArgumentValue,
	show: ArgumentValue,
	silent: ArgumentValue,
	silentlog: ArgumentValue,
	smooth: ArgumentValue,
	textonly: ArgumentValue,
	top: ArgumentValue,
	true: ArgumentValue,
	try: ArgumentValue,
	'un.components': ArgumentValue,
	'un.custom': ArgumentValue,
	'un.directory': ArgumentValue,
	'un.instfiles': ArgumentValue,
	'un.license': ArgumentValue,
	uninstConfirm: ArgumentValue,
	user: ArgumentValue,
	Win10: ArgumentValue,
	Win7: ArgumentValue,
	Win8: ArgumentValue,
	WinVista: ArgumentValue,
	'x86-ansi': ArgumentValue,
	'x86-unicode': ArgumentValue,
	zlib: ArgumentValue,
};

const keywordsLower: Record<string, number> = Object.create(null);
for (const [k, v] of Object.entries(keywords)) {
	keywordsLower[k.toLowerCase()] = v;
}

const isConstant = /^[A-Z][A-Z0-9_]+$/;

export function specializeIdentifier(value: string) {
	return keywords[value] ?? (isConstant.test(value) ? Constant : -1);
}

export function specializeIdentifierLoose(value: string) {
	return keywordsLower[value.toLowerCase()] ?? (isConstant.test(value) ? Constant : -1);
}
