/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: NSIS definitions */

/**
 * Maps lowercased instruction parameters to their canonical casing.
 *
 * Generated from @nsis/dent-spec 0.0.0 by `npm run codegen` — do not edit.
 */

export const globalParameters: Map<string, string> = new Map([
	['/a', '/a'],
	['/bom', '/BOM'],
	['/branding', '/BRANDING'],
	['/componentsonlyoncustom', '/COMPONENTSONLYONCUSTOM'],
	['/date', '/date'],
	['/e', '/e'],
	['/enablecancel', '/ENABLECANCEL'],
	['/exeresource', '/EXERESOURCE'],
	['/file', '/file'],
	['/fileexists', '/FILEEXISTS'],
	['/filesonly', '/FILESONLY'],
	['/final', '/FINAL'],
	['/global', '/GLOBAL'],
	['/ifempty', '/ifempty'],
	['/ifndef', '/ifndef'],
	['/ifnosubkeys', '/ifnosubkeys'],
	['/ifnovalues', '/ifnovalues'],
	['/ignorecase', '/ignorecase'],
	['/intfmt', '/intfmt'],
	['/italic', '/ITALIC'],
	['/math', '/math'],
	['/nocustom', '/NOCUSTOM'],
	['/noerrors', '/NOERRORS'],
	['/nonfatal', '/NONFATAL'],
	['/nounload', '/nounload'],
	['/noworkingdir', '/NoWorkingDir'],
	['/o', '/o'],
	['/overwrite', '/OVERWRITE'],
	['/packed', '/packed'],
	['/plugin', '/plugin'],
	['/productversion', '/ProductVersion'],
	['/r', '/r'],
	['/rawnl', '/RAWNL'],
	['/rebootok', '/REBOOTOK'],
	['/redef', '/redef'],
	['/regedit5', '/REGEDIT5'],
	['/replace', '/REPLACE'],
	['/resizetofit', '/RESIZETOFIT'],
	['/resizetofitheight', '/RESIZETOFITHEIGHT'],
	['/resizetofitwidth', '/RESIZETOFITWIDTH'],
	['/sd', '/SD'],
	['/short', '/SHORT'],
	['/silent', '/SILENT'],
	['/solid', '/SOLID'],
	['/strike', '/STRIKE'],
	['/stringid', '/STRINGID'],
	['/target', '/target'],
	['/trimcenter', '/TRIMCENTER'],
	['/trimleft', '/TRIMLEFT'],
	['/trimright', '/TRIMRIGHT'],
	['/underline', '/UNDERLINE'],
	['/uninstcomponentsonlyoncustom', '/UNINSTCOMPONENTSONLYONCUSTOM'],
	['/uninstnocustom', '/UNINSTNOCUSTOM'],
	['/utcdate', '/utcdate'],
	['/windows', '/windows'],
	['/x', '/x'],
]);

export const globalParameterPrefixes: Map<string, string> = new Map([
	['/charset=', '/CHARSET='],
	['/customstring=', '/CUSTOMSTRING='],
	['/imgid=', '/IMGID='],
	['/lang=', '/LANG='],
	['/oname=', '/oname='],
	['/timeout=', '/TIMEOUT='],
	['/uninstcustomstring=', '/UNINSTCUSTOMSTRING='],
]);

export const instructionParameters: ReadonlyMap<string, ReadonlyMap<string, string>> = new Map([
	[
		'addbrandingimage',
		new Map([
			['bottom', 'bottom'],
			['left', 'left'],
			['right', 'right'],
			['top', 'top'],
		]),
	],
	[
		'allowrootdirinstall',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'allowskipfiles',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'autoclosewindow',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'changeui',
		new Map([
			['dlg_id', 'dlg_id'],
		]),
	],
	[
		'crccheck',
		new Map([
			['false', 'false'],
			['off', 'off'],
			['on', 'on'],
			['true', 'true'],
		]),
	],
	[
		'createshortcut',
		new Map([
			['alt', 'ALT'],
			['control', 'CONTROL'],
			['ext', 'EXT'],
			['shift', 'SHIFT'],
			['sw_hide', 'SW_HIDE'],
			['sw_show', 'SW_SHOW'],
			['sw_showmaximized', 'SW_SHOWMAXIMIZED'],
			['sw_showminimized', 'SW_SHOWMINIMIZED'],
			['sw_shownormal', 'SW_SHOWNORMAL'],
		]),
	],
	[
		'deleteregkey',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'deleteregvalue',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'dirshow',
		new Map([
			['hide', 'hide'],
			['show', 'show'],
		]),
	],
	[
		'dirverify',
		new Map([
			['auto', 'auto'],
			['leave', 'leave'],
		]),
	],
	[
		'enumregkey',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'enumregvalue',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'execshell',
		new Map([
			['open', 'open'],
			['print', 'print'],
		]),
	],
	[
		'execshellwait',
		new Map([
			['open', 'open'],
			['print', 'print'],
		]),
	],
	[
		'fileopen',
		new Map([
			['a', 'a'],
			['r', 'r'],
			['w', 'w'],
		]),
	],
	[
		'fileseek',
		new Map([
			['cur', 'CUR'],
			['end', 'END'],
			['set', 'SET'],
		]),
	],
	[
		'getwinver',
		new Map([
			['build', 'BUILD'],
			['major', 'MAJOR'],
			['minor', 'MINOR'],
			['servicepack', 'SERVICEPACK'],
		]),
	],
	[
		'installdirregkey',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'instprogressflags',
		new Map([
			['colored', 'colored'],
			['smooth', 'smooth'],
		]),
	],
	[
		'licenseforceselection',
		new Map([
			['checkbox', 'checkbox'],
			['off', 'off'],
			['on', 'on'],
			['radiobuttons', 'radiobuttons'],
		]),
	],
	[
		'lockwindow',
		new Map([
			['off', 'off'],
			['on', 'on'],
		]),
	],
	[
		'logset',
		new Map([
			['off', 'off'],
			['on', 'on'],
		]),
	],
	[
		'manifestdisablewindowfiltering',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'manifestdpiaware',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'manifestgdiscaling',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'manifestlongpathaware',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'manifestsupportedos',
		new Map([
			['win10', 'Win10'],
			['win7', 'Win7'],
			['win8', 'Win8'],
			['win8.1', 'Win8.1'],
			['winvista', 'WinVista'],
		]),
	],
	[
		'messagebox',
		new Map([
			['idabort', 'IDABORT'],
			['idcancel', 'IDCANCEL'],
			['idignore', 'IDIGNORE'],
			['idno', 'IDNO'],
			['idok', 'IDOK'],
			['idretry', 'IDRETRY'],
			['idyes', 'IDYES'],
			['mb_abortretryignore', 'MB_ABORTRETRYIGNORE'],
			['mb_defbutton1', 'MB_DEFBUTTON1'],
			['mb_defbutton2', 'MB_DEFBUTTON2'],
			['mb_defbutton3', 'MB_DEFBUTTON3'],
			['mb_defbutton4', 'MB_DEFBUTTON4'],
			['mb_iconexclamation', 'MB_ICONEXCLAMATION'],
			['mb_iconinformation', 'MB_ICONINFORMATION'],
			['mb_iconquestion', 'MB_ICONQUESTION'],
			['mb_iconstop', 'MB_ICONSTOP'],
			['mb_ok', 'MB_OK'],
			['mb_okcancel', 'MB_OKCANCEL'],
			['mb_retrycancel', 'MB_RETRYCANCEL'],
			['mb_right', 'MB_RIGHT'],
			['mb_setforeground', 'MB_SETFOREGROUND'],
			['mb_topmost', 'MB_TOPMOST'],
			['mb_usericon', 'MB_USERICON'],
			['mb_yesno', 'MB_YESNO'],
			['mb_yesnocancel', 'MB_YESNOCANCEL'],
		]),
	],
	[
		'page',
		new Map([
			['components', 'components'],
			['custom', 'custom'],
			['directory', 'directory'],
			['instfiles', 'instfiles'],
			['license', 'license'],
			['uninstconfirm', 'uninstConfirm'],
		]),
	],
	[
		'readregdword',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'readregstr',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'requestexecutionlevel',
		new Map([
			['admin', 'admin'],
			['highest', 'highest'],
			['none', 'none'],
			['user', 'user'],
		]),
	],
	[
		'setautoclose',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'setcompress',
		new Map([
			['auto', 'auto'],
			['force', 'force'],
			['off', 'off'],
			['on', 'on'],
		]),
	],
	[
		'setcompressor',
		new Map([
			['bzip2', 'bzip2'],
			['lzma', 'lzma'],
			['zlib', 'zlib'],
		]),
	],
	[
		'setctlcolors',
		new Map([
			['transparent', 'transparent'],
		]),
	],
	[
		'setdatablockoptimize',
		new Map([
			['false', 'false'],
			['off', 'off'],
			['on', 'on'],
			['true', 'true'],
		]),
	],
	[
		'setdatesave',
		new Map([
			['false', 'false'],
			['off', 'off'],
			['on', 'on'],
			['true', 'true'],
		]),
	],
	[
		'setdetailsprint',
		new Map([
			['both', 'both'],
			['lastused', 'lastused'],
			['listonly', 'listonly'],
			['none', 'none'],
			['textonly', 'textonly'],
		]),
	],
	[
		'setdetailsview',
		new Map([
			['hide', 'hide'],
			['show', 'show'],
		]),
	],
	[
		'setfileattributes',
		new Map([
			['archive', 'ARCHIVE'],
			['hidden', 'HIDDEN'],
			['offline', 'OFFLINE'],
			['readonly', 'READONLY'],
			['system', 'SYSTEM'],
			['temporary', 'TEMPORARY'],
		]),
	],
	[
		'setoverwrite',
		new Map([
			['ifdiff', 'ifdiff'],
			['ifnewer', 'ifnewer'],
			['lastused', 'lastused'],
			['off', 'off'],
			['on', 'on'],
			['try', 'try'],
		]),
	],
	[
		'setpluginunload',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'setregview',
		new Map([
			['default', 'default'],
		]),
	],
	[
		'setshellvarcontext',
		new Map([
			['all', 'all'],
			['current', 'current'],
		]),
	],
	[
		'setsilent',
		new Map([
			['normal', 'normal'],
			['silent', 'silent'],
		]),
	],
	[
		'showinstdetails',
		new Map([
			['hide', 'hide'],
			['nevershow', 'nevershow'],
			['show', 'show'],
		]),
	],
	[
		'showuninstdetails',
		new Map([
			['hide', 'hide'],
			['nevershow', 'nevershow'],
			['show', 'show'],
		]),
	],
	[
		'showwindow',
		new Map([
			['sw_hide', 'SW_HIDE'],
			['sw_show', 'SW_SHOW'],
			['sw_showmaximized', 'SW_SHOWMAXIMIZED'],
			['sw_showminimized', 'SW_SHOWMINIMIZED'],
			['sw_shownormal', 'SW_SHOWNORMAL'],
		]),
	],
	[
		'silentinstall',
		new Map([
			['normal', 'normal'],
			['silent', 'silent'],
			['silentlog', 'silentlog'],
		]),
	],
	[
		'silentuninstall',
		new Map([
			['normal', 'normal'],
			['silent', 'silent'],
		]),
	],
	[
		'target',
		new Map([
			['amd64', 'amd64'],
			['x86', 'x86'],
		]),
	],
	[
		'unicode',
		new Map([
			['false', 'false'],
			['true', 'true'],
		]),
	],
	[
		'uninstpage',
		new Map([
			['components', 'components'],
			['custom', 'custom'],
			['directory', 'directory'],
			['instfiles', 'instfiles'],
			['license', 'license'],
			['uninstconfirm', 'uninstConfirm'],
		]),
	],
	[
		'windowicon',
		new Map([
			['false', 'false'],
			['off', 'off'],
			['on', 'on'],
			['true', 'true'],
		]),
	],
	[
		'writeregbin',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'writeregdword',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'writeregexpandstr',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'writeregmultistr',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'writeregnone',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'writeregstr',
		new Map([
			['hkcc', 'HKCC'],
			['hkcr', 'HKCR'],
			['hkcr32', 'HKCR32'],
			['hkcr64', 'HKCR64'],
			['hkcu', 'HKCU'],
			['hkcu32', 'HKCU32'],
			['hkcu64', 'HKCU64'],
			['hkdd', 'HKDD'],
			['hklm', 'HKLM'],
			['hklm32', 'HKLM32'],
			['hklm64', 'HKLM64'],
			['hkpd', 'HKPD'],
			['hku', 'HKU'],
			['shctx', 'SHCTX'],
		]),
	],
	[
		'xpstyle',
		new Map([
			['off', 'off'],
			['on', 'on'],
		]),
	],
]);
