name: "Run tests on NodeJS"

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**/e2e/**"
      - "**/src/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "vitest.config.ts"
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        node-version: ["24"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 10

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_store_path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Set up pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Lint Source
        run: pnpm run --if-present --recursive lint:biome:ci

      - name: Build Source
        run: pnpm run --if-present build

      - name: Install Playwright browsers
        run: pnpm --filter @nsis/dent-ui exec playwright install --with-deps chromium

      - name: Run Tests
        run: pnpm run --if-present test
